use crate::types::{Action, Filter};

pub const FILTERS: [(&str, Filter); 3] = [
    ("All", Filter::All),
    ("Pending", Filter::Pending),
    ("Completed", Filter::Completed),
];

pub const KEYBINDINGS: &[&str] = &[
    "BROWSING",
    "  ?             Open keybindings help",
    "  0             Focus the right preview",
    "  1 / 2 / 3     Focus Inbox / Projects / Commits",
    "  Up / Down     Move selection; scroll commit details",
    "  Left / Right  Cycle sidebar sections (left panel only)",
    "  Enter         Open preview; edit a task in Tasks",
    "  Esc           Return to sidebar; no effect when already there",
    "  Ctrl+K        Search tasks and actions",
    "  c             Create a SQLite checkpoint from any panel",
    "  q             Quit; wait for sync to finish first",
    "",
    "TASKS AND PROJECTS",
    "  a             Add task; add project in Projects",
    "  e             Edit task; rename project in Projects",
    "  Space         Complete/reopen task (Tasks only)",
    "  d             Delete task/project with confirmation",
    "  m             Move task to Inbox/project (Tasks only)",
    "  Shift+D       Nuke all data, local commits and remote settings",
    "",
    "COMMITS (LEFT PANEL)",
    "  r             Set/change/remove origin",
    "  p             Push committed snapshots",
    "  Shift+P       Safely pull and apply the latest snapshot",
    "",
    "TEXT ENTRY, SEARCH AND MOVE",
    "  Typing        Append text/search, including ? and shortcut letters",
    "  Backspace     Remove last character",
    "  Enter         Save title/text; run search result; choose destination",
    "  Enter         Insert newline when task Description is focused",
    "  Tab           Toggle task Title/Description",
    "  Ctrl+S        Save task from Description",
    "  Up / Down     Choose search result or move destination",
    "  Esc           Cancel dialog/search/move",
    "  Ctrl+K        Close palette; does not interrupt other dialogs",
    "  Empty origin  Save empty input to remove remote settings",
    "  Enter / Esc   Close the no-changes commit popup",
    "",
    "CONFIRMATIONS",
    "  Enter         Confirm task/project deletion or nuke",
    "  Esc           Cancel task/project deletion or nuke",
    "",
    "KEYBINDINGS HELP",
    "  Up / Down     Scroll one line",
    "  PageUp/Down   Scroll one page",
    "  Home / End    Jump to first/last page",
    "  ? / Esc       Close help; return to the previous focus",
    "  Tab           Disabled while browsing",
];

pub(crate) const ACTIONS: [(&str, Action); 9] = [
    ("Add task", Action::Add),
    ("Edit selected task", Action::Edit),
    ("Complete / reopen selected task", Action::ToggleCompletion),
    ("Delete selected task", Action::Delete),
    ("Move selected task", Action::Move),
    ("Show all tasks", Action::ShowFilter(0)),
    ("Show pending tasks", Action::ShowFilter(1)),
    ("Show completed tasks", Action::ShowFilter(2)),
    ("Quit", Action::Quit),
];
